#!/usr/bin/perl -w

sub catch_zap {
    my $signame = shift;
    print "received SIG$signame, ignoring\n";
}

$SIG{TERM} = \&catch_zap;

$_ = <STDIN>;
chop;
print "received stdin input of '$_'\n";
print "exiting\n";
