#!/usr/bin/perl -w

# handy test program to run.  prints a number each second

# uncomment this to turn on autoflush of stdout (which is cheating :) )
#$| = 1;

$i = 0;

$id = "";
if (defined($ARGV[0])) {
    $id = " $ARGV[0]";
}
if (defined($ENV{COUNTER})) {
    print "counter$id: \$COUNTER = $ENV{COUNTER}\n";
} else {
    print "counter$id: \$COUNTER not defined\n";
}

while (1) {
    print "counter$id: $i\n";
    $i++;
    sleep(1);
}
