######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 30 22:02:45 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
